In [1]:
lst = [2,3,5,8,9,12]

In [2]:
# lst[0] +=2
# lst[1] +=2

for i in range(6):
    print(i)

0
1
2
3
4
5


In [4]:
for i in range(len(lst)):
    lst[i] +=2   # bytecode

In [5]:
lst

[4, 5, 7, 10, 11, 14]

In [ ]:
# lst, dic
# tuple,set

In [6]:
# numpy core data structure ndarray -> array

In [7]:
import numpy as np

# array = np.genfromtxt(, delimiter = ",")

In [10]:
ar = np.array([2,3,5,8,9,12])

In [11]:
ar

array([ 2,  3,  5,  8,  9, 12])

In [12]:
# CPU, GPU, TPU, QPU

numpy array use processor feature SIMD (single instruction Multiple Data) to perform operation. This process will replace loop and this process is called vectorized operation

In [14]:
ar + 2

array([ 4,  5,  7, 10, 11, 14])

In [15]:
array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [8,9,10,11]])

Numpy attributes

1. dtype
2. ndim
3. shape

In [17]:
array.dtype

dtype('int32')

In [18]:
array.ndim

2

In [19]:
array.shape

(3, 4)

In [20]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 8,  9, 10, 11]])

In [21]:
lolst = [[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 8,  9, 10, 11]]

In [22]:
lolst

[[1, 2, 3, 4], [5, 6, 7, 8], [8, 9, 10, 11]]

In [23]:
lolst[0][1]

2

In [24]:
lolst[1][-1]

8

In [25]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 8,  9, 10, 11]])

In [26]:
array[0][1]

2

In [27]:
array[0,1]

2

In [28]:
array[[0,2],]

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [29]:
array[[0,2]]

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [30]:
array[[0,2],1]

array([2, 9])

In [32]:
array[:,[0,-1]]

array([[ 1,  4],
       [ 5,  8],
       [ 8, 11]])

In [33]:
array[:,0] + array[:,-1]

array([ 5, 13, 19])

In [35]:
print(lolst)

[[1, 2, 3, 4], [5, 6, 7, 8], [8, 9, 10, 11]]


In [36]:
l = []

for i in lolst:
    add = i[0]+ i[-1]
    l.append(add)

In [38]:
l

[5, 13, 19]

In [39]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 8,  9, 10, 11]])

In [40]:
l= []

for i in lolst:
    s = i[1]
    if s == 6:
        l.append(i)

In [41]:
l

[[5, 6, 7, 8]]

In [44]:
array[:,1]==6 # it will return you a booleans array

array([False,  True, False])

In [45]:
bol = array[:,1]==6

In [46]:
array[bol,]

array([[5, 6, 7, 8]])

In [47]:
array[bol] # boolean indexing . its actually help to avoid writing conditional statement

array([[5, 6, 7, 8]])

In [49]:
bol1 = array[:,1]==6  # or |
bol2 = array[:,1]==9

array[bol1 |bol2] # 

array([[ 5,  6,  7,  8],
       [ 8,  9, 10, 11]])

In [52]:
array[(array[:,1] == 6) & (array[:,-1] == 9) ] # and &

array([], shape=(0, 4), dtype=int32)

In [53]:
array[(array[:,1] == 6) & (array[:,-1] == 8) ]

array([[5, 6, 7, 8]])